# Generated by Django 5.0.4 on 2024-05-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tag_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsreg',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentsreg',
            old_name='studentId',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='studentsreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
