# Generated by Django 5.0.4 on 2024-05-19 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_courseid_studentsreg_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsreg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
