# Generated by Django 5.0.4 on 2024-05-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_studentsreg_completed_remove_course_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsreg',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_for', to='app.course'),
        ),
    ]
